name: destiny
description: An package which generates mock-data using the PCG algorithm.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  english_words: ^4.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  benchmark_harness: any

