name: destiny
description: An package which generates mock-data using the PCG algorithm.
version: 0.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  english_words: ^3.1.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  instant: any
